92 2j add poi
Bouboule-Corp/thurii-mobile-kotlin pull request #121
Opened 2022-08-22 17:27 UTC by claraxuxu

2022-08-22 17:27 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/HomePage/HomePageFragments/MapFragment.kt
> +import android.Manifest
🚫 **[ktlint]** <import-ordering> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Imports must be ordered in lexicographic order without any empty lines in-between with "java", "javax", "kotlin" and aliases in the end

2022-08-22 17:27 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/HomePage/HomePageFragments/MapFragment.kt
> +import android.os.PersistableBundle
🚫 **[ktlint]** <no-unused-imports> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unused import

2022-08-22 17:27 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/HomePage/HomePageFragments/MapFragment.kt
> +        val filterButtonList = arrayListOf<map_recyclerview_item>() //list of buttons
🚫 **[ktlint]** <comment-spacing> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing space after //

2022-08-22 17:27 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/HomePage/HomePageFragments/MapFragment.kt
> +            filterButtonList, R.layout.item_on_board, requireContext()
🚫 **[ktlint]** <argument-list-wrapping> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Argument should be on a separate line (unless all arguments can fit a single line)

2022-08-22 17:27 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/HomePage/HomePageFragments/MapFragment.kt
> +            filterButtonList, R.layout.item_on_board, requireContext()
🚫 **[ktlint]** <argument-list-wrapping> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Argument should be on a separate line (unless all arguments can fit a single line)

2022-08-22 17:27 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/HomePage/HomePageFragments/MapFragment.kt
> +        if ((ContextCompat.checkSelfPermission(
🚫 **[ktlint]** <wrapping> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing newline after "("

2022-08-22 17:27 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/HomePage/HomePageFragments/MapFragment.kt
> +                Manifest.permission.ACCESS_FINE_LOCATION) != PackageManager.PERMISSION_GRANTED)
🚫 **[ktlint]** <wrapping> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing newline before ")"

2022-08-22 17:27 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/HomePage/HomePageFragments/MapFragment.kt
> +                Manifest.permission.ACCESS_FINE_LOCATION) != PackageManager.PERMISSION_GRANTED)
🚫 **[ktlint]** <argument-list-wrapping> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing newline before ")"

2022-08-22 17:27 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/HomePage/HomePageFragments/MapFragment.kt
> +                Manifest.permission.ACCESS_FINE_LOCATION) != PackageManager.PERMISSION_GRANTED)
🚫 **[ktlint]** <wrapping> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing newline before ")"

2022-08-22 17:27 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/HomePage/HomePageFragments/MapFragment.kt
> +        else {
🚫 **[ktlint]** <keyword-spacing> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected newline before "else"

2022-08-22 17:27 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/data/map_recyclerview_item_adapter.kt
> +package com.bouboulecorp.thurii.data
🚫 **[ktlint]** <final-newline> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>File must end with a newline (\n)

2022-08-22 17:27 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/data/map_recyclerview_item_adapter.kt
> +    private val filterButtonList: List<map_recyclerview_item>, private val layoutId: Int, private val cont : Context
🚫 **[ktlint]** <parameter-list-wrapping> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Parameter should be on a separate line (unless all parameters can fit a single line)

2022-08-22 17:27 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/data/map_recyclerview_item_adapter.kt
> +    private val filterButtonList: List<map_recyclerview_item>, private val layoutId: Int, private val cont : Context
🚫 **[ktlint]** <parameter-list-wrapping> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Parameter should be on a separate line (unless all parameters can fit a single line)

2022-08-22 17:27 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/data/map_recyclerview_item_adapter.kt
> +    private val filterButtonList: List<map_recyclerview_item>, private val layoutId: Int, private val cont : Context
🚫 **[ktlint]** <colon-spacing> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected spacing before ":"

2022-08-22 17:27 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/data/map_recyclerview_item_adapter.kt
> +{
🚫 **[ktlint]** <curly-spacing> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected newline before "{"

2022-08-22 17:27 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/data/map_recyclerview_item_adapter.kt
> +        val button : ImageButton = view.findViewById(R.id.imageButtonItem)
🚫 **[ktlint]** <colon-spacing> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected spacing before ":"

2022-08-22 17:35 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/HomePage/HomePageFragments/MapFragment.kt
> +            (ContextCompat.checkSelfPermission(
🚫 **[ktlint]** <wrapping> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing newline after "("

2022-08-22 17:35 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/HomePage/HomePageFragments/MapFragment.kt
> +                    )
🚫 **[ktlint]** <indent> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected indentation (20) (should be 16)

2022-08-22 17:35 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/data/map_recyclerview_item_adapter.kt
> +): RecyclerView.Adapter<map_recyclerview_item_adapter.ViewHolder>() {
🚫 **[ktlint]** <colon-spacing> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing spacing before ":"

2022-08-22 17:35 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/data/map_recyclerview_item_adapter.kt
> +    class ViewHolder(view: View): RecyclerView.ViewHolder(view) {
🚫 **[ktlint]** <colon-spacing> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing spacing before ":"

2022-08-22 17:39 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/HomePage/HomePageFragments/MapFragment.kt
> +                requireContext(),
🚫 **[ktlint]** <indent> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected indentation (16) (should be 20)

2022-08-22 17:39 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/HomePage/HomePageFragments/MapFragment.kt
> +                Manifest.permission.ACCESS_FINE_LOCATION
🚫 **[ktlint]** <indent> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected indentation (16) (should be 20)

2022-08-22 17:39 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/HomePage/HomePageFragments/MapFragment.kt
> +            ) != PackageManager.PERMISSION_GRANTED
🚫 **[ktlint]** <indent> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected indentation (12) (should be 16)

2022-08-22 17:58 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/HomePage/HomePageFragments/MapFragment.kt
> +            )
🚫 **[ktlint]** <indent> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected indentation (12) (should be 16)

2022-08-23 07:53 UTC, larroyo3 requested changes
il me semble que la bar pour filtrer les POI n'est pas à faire sur cette PR

tu peux la garder de coté pour ta prochaine issue "Filter POI" mais je pense c'est mieux de pas mélanger les issues et de l'enlever de celle ci

2022-08-23 19:40 UTC, claraxuxu commented
> il me semble que la bar pour filtrer les POI n'est pas à faire sur cette PR
> 
> tu peux la garder de coté pour ta prochaine issue "Filter POI" mais je pense c'est mieux de pas mélanger les issues et de l'enlever de celle ci

t'as bien raison, je viens de push une version propre

2022-08-24 08:26 UTC, larroyo3 requested changes
Est-ce que c'est possible d'avoir les icon en svg plutot qu'en png ? 
Sinon c'est tout bon pour moi :+1:

2022-08-24 20:43 UTC, claraxuxu commented
- [ ] les îcons de POI en formate texte(emoji) arrivent pas à être exporter correctement à format SVG

2022-08-24 20:43 UTC, merged