79 6j registration
Bouboule-Corp/thurii-mobile-kotlin pull request #129
Opened 2022-09-05 14:07 UTC by claraxuxu

some corrections for the first design version

2022-09-05 14:08 UTC, Neyross commented on app/src/androidTest/java/com/bouboulecorp/thurii/DoubleAuth/TelCheckCodeActivityTest.kt
> +import androidx.test.core.app.ActivityScenario
🚫 **[ktlint]** <import-ordering> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Imports must be ordered in lexicographic order without any empty lines in-between with "java", "javax", "kotlin" and aliases in the end

2022-09-05 14:08 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/DoubleAuth/DoubleAuthActivity.kt
> +import android.widget.*
🚫 **[ktlint]** <no-wildcard-imports> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Wildcard import (cannot be auto-corrected)

2022-09-05 14:08 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/DoubleAuth/TelCheckCodeActivity.kt
> +                    as InputMethodManager
🚫 **[ktlint]** <indent> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected indentation (20) (should be 16)

2022-09-05 14:08 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/Onboarding/OnboardingActivity.kt
> +package com.bouboulecorp.thurii.Onboarding
🚫 **[ktlint]** <final-newline> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>File must end with a newline (\n)

2022-09-05 14:08 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/Onboarding/OnboardingActivity.kt
> +class OnboardingActivity: AppCompatActivity() {
🚫 **[ktlint]** <colon-spacing> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing spacing before ":"

2022-09-05 14:08 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/Registration/RegistrationFragment/FragmentRegistrationGender.kt
> +
🚫 **[ktlint]** <no-consecutive-blank-lines> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Needless blank line(s)

2022-09-05 14:53 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/DoubleAuth/DoubleAuthActivity.kt
> +import android.content.Intent
🚫 **[ktlint]** <import-ordering> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Imports must be ordered in lexicographic order without any empty lines in-between with "java", "javax", "kotlin" and aliases in the end

2022-09-05 16:06 UTC, larroyo3 approved these changes

2022-09-06 07:49 UTC, Neyross requested changes
les test instrumente fails je pense que tu as pas enleve les anciens et que c'est pour ca

2022-09-06 09:05 UTC, Neyross approved these changes
ca va qu'il y a pas de limite sur le coverage pour le moment mais il va falloir avoir plus les porchaines fois

2022-09-06 09:10 UTC, merged