90 2j add localisation
Bouboule-Corp/thurii-mobile-kotlin pull request #141
Opened 2022-09-20 03:33 UTC by Neyross

2022-09-20 03:34 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/HomePage/HomePageFragments/MapFragment.kt
> +import android.Manifest
🚫 **[ktlint]** <import-ordering> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Imports must be ordered in lexicographic order without any empty lines in-between with "java", "javax", "kotlin" and aliases in the end

2022-09-20 03:34 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/HomePage/HomePageFragments/MapFragment.kt
> +import androidx.core.app.ActivityCompat
🚫 **[ktlint]** <no-unused-imports> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unused import

2022-09-20 03:34 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/HomePage/HomePageFragments/MapFragment.kt
> +import androidx.core.content.ContextCompat
🚫 **[ktlint]** <no-unused-imports> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unused import

2022-09-20 03:34 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/HomePage/HomePageFragments/MapFragment.kt
> +import androidx.core.content.PermissionChecker.PERMISSION_GRANTED
🚫 **[ktlint]** <no-unused-imports> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unused import

2022-09-20 03:34 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/HomePage/HomePageFragments/MapFragment.kt
> +        locationOverlay.runOnFirstFix(){ (context as MainActivity).runOnUiThread {
🚫 **[ktlint]** <curly-spacing> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing spacing before "{"

2022-09-20 03:34 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/HomePage/HomePageFragments/MapFragment.kt
> +        locationOverlay.runOnFirstFix(){ (context as MainActivity).runOnUiThread {
🚫 **[ktlint]** <wrapping> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing newline after "{"

2022-09-20 03:34 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/HomePage/HomePageFragments/MapFragment.kt
> +        }}
🚫 **[ktlint]** <wrapping> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing newline before "}"

2022-09-20 03:34 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/HomePage/HomePageFragments/MapFragment.kt
> +        }}
🚫 **[ktlint]** <curly-spacing> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing spacing after "}"

2022-09-20 03:34 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/HomePage/HomePageFragments/MapFragment.kt
> +        }}
🚫 **[ktlint]** <curly-spacing> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing spacing before "}"

2022-09-20 11:23 UTC, larroyo3 requested changes
plusieurs problème du linter

2022-10-05 10:14 UTC, larroyo3 approved these changes
:ok_hand:

2022-10-05 10:54 UTC, claraxuxu approved these changes

2022-10-07 02:36 UTC, merged