162 05j geolocalisation button
Bouboule-Corp/thurii-mobile-kotlin pull request #203
Opened 2022-11-22 03:37 UTC by Neyross

2022-11-28 05:12 UTC, Neyross commented
![image](https://user-images.githubusercontent.com/74605059/204198919-fd515dec-d2b7-4407-8aa4-44718bf0a6b5.png)

2022-11-28 15:19 UTC, claraxuxu approved these changes

2022-11-28 20:05 UTC, larroyo3 requested changes
C'est quoi les 2 images quand tu as changer dans les pages de welcome ? 

Et sinon si je chipote pour que la maquette soit respecter faudrait un padding right sur le bouton, je sais pas sur ton tel mais sur le miens il est collé au bord de l'écran alors que sur la maquette il a un petit padding.

Et sinon ça on en a parler mais il faudrait la version thème sombre du bouton (je peux te le faire si besoin)

2023-01-11 10:39 UTC, larroyo3 approved these changes

2023-01-11 10:39 UTC, merged