164 3j map detail page UI
Bouboule-Corp/thurii-mobile-kotlin pull request #206
Opened 2022-11-30 11:10 UTC by claraxuxu

2022-11-30 13:02 UTC, larroyo3 requested changes
GG pour moi c'est quasi tout bon y a juste quelque petit détails par rapport à la maquette : 

- le fond de map details est pas de la meme couleur que le reste (si tu veux un example de comment y ajouter c'est tout simple tu peux aller voir sur le xml de l'activity login ligne 8)
- sur la maquette map détails à un gradient de plus en plus transparent sur cette page si c'est possible à faire
- un mini truc : le dernier bouton pas le même écartement avec le reste, je crois tu as oublier de rajouter un margin comme tu as mi les autres
- et si c'est possible quand on clique sur le petit bouton settings de la bar de recharge ça ouvre/ferme map details

Si jamais c'est pas possible à faire ou y a des trucs que j'ai dis que tu a pas compris hésite pas à me redire. :+1:

2022-12-05 15:56 UTC, larroyo3 requested changes
Stylé le gradient :+1:  mais il est peu trop fort j'ai l'impression par rapport à la maquette ( y a les valeurs exact sur le maquette) après si tu l'as fait comme sur la maquette désoler d'avance

Y a un petit bug quand on baisse map detail le gradient est toujours la

Et toujours le même truc qu'avant si c'est possible de ça serait bien de pouvoir ouvrir/fermer map details en appuyant sur le bouton settings de la searchbar

2022-12-06 11:11 UTC, Neyross requested changes
il manque une capture d'ecran des test unitaire

2022-12-12 14:59 UTC, claraxuxu commented
@larroyo3 bug de background est fixé, et le map detail peut être fermer/ouvrir en cliquant sur le bouton setting de search bar

2022-12-15 13:03 UTC, larroyo3 requested changes
Dernier petit bug sur la couleur du bouton settings

2022-12-19 05:54 UTC, merged