Fix env GitHub
Bouboule-Corp/thurii-mobile-kotlin pull request #74
Opened 2022-06-15 13:12 UTC by Neyross

closes #73

2022-06-20 22:09 UTC, Neyross commented on app/src/main/java/com/bouboulecorp/thurii/HomePage/HomePageFragments/MapFragment.kt
> +import com.bouboulecorp.thurii.BuildConfig
🚫 **[ktlint]** <no-unused-imports> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unused import

2022-06-21 07:46 UTC, Neyross commented on app/src/androidTest/java/com/bouboulecorp/thurii/EmailRegistration/RegisterEmailActivityTest.kt
> +            .check(matches(withText(R.string.btn_continue))
🚫 **[ktlint]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Not a valid Kotlin file (85:60 expecting ')') (cannot be auto-corrected)

2022-06-21 09:21 UTC, larroyo3 requested changes
C'est tout bon pour moi appart le bout de doc

Je pense que c'est mieux de l'avoir dans le readme (le readme est la pour expliquer comment lancer le projet et setup les variable d'env servent à ça aussi)
Genre ça pourrait être une nouvelle partie entre "Android Studio IDE setup" et le "Getting started"

Et essaye de faire comme les autres doc, c'est à dire mettre directement des explications de comment faire plutôt que juste mettre un lien sans aucune explication (tu peux prendre exemple sur le reamde ou sur la partie JUnit pour les tests unitaires). Mettre juste un lien c'est pas vraiment une doc

2022-06-21 10:44 UTC, claraxuxu reviewed
tout est ok pour moi

2022-06-22 08:11 UTC, larroyo3 approved these changes
Good job :+1:

2022-06-22 08:14 UTC, merged